apiVersion: v1
kind: Service
metadata:
  name: asgn-10-java-app
  labels:
    app: asgn-10-java-app
    release: monitoring

spec:
  type: {{ .Values.service.type }}
  selector:
    app: asgn-10-java-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}

      
