name: CI-CD Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  pipeline:
    runs-on: self-hosted

    steps:

    
      - name: Checkout Repository
        uses: actions/checkout@v4

      
      - name: Clean workspace
        run: rm -rf app/build


      - name: Build using gradle-container
        run: |
            docker exec gradle-container bash -c "
            rm -rf /tmp/app &&
            mkdir -p /tmp/app
            "

            docker cp $PWD/app gradle-container:/tmp/

            docker exec gradle-container bash -c "
            cd /tmp/app &&
            chmod +x gradlew &&
            ./gradlew clean build
            "


      - name: Copy JAR from container
        run: |
          mkdir -p app/build/libs
          docker cp gradle-container:/tmp/app/build/libs/. app/build/libs/


      - name: SonarQube Analysis
        run: |
          docker exec gradle-container bash -c "
            cd /tmp/app &&
            ./gradlew sonarqube \
              -Dsonar.host.url=${{ secrets.SONAR_HOST }} \
              -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          "

 
          

      - name: Sonar Quality Gate
        run: |
          
          sleep 30

          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
          "${{ secrets.SONAR_HOST }}/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" \
          | grep -o '"status":"OK"')

          echo "Quality Gate: $STATUS"

          if [ -z "$STATUS" ]; then
            echo "Quality Gate Failed"
            exit 1
          fi

  
      - name: Build Docker Image
        run: |
          docker build -t ashirqayyum/asgn-10-java-app:latest .

    
      - name: Push Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ashirqayyum/asgn-10-java-app:latest

     
      - name: Deploy to AWS via SSH + Helm
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'

            cd ~/devops-cloudnative-assignment

            echo "Pull latest image"
            docker pull ashirqayyum/asgn-10-java-app:latest

            echo "Upgrade Helm release"
            helm upgrade java-app ./helm/java-app \
              --set image.repository=ashirqayyum/asgn-10-java-app \
              --set image.tag=latest

            echo "Wait for rollout"
            kubectl rollout status deployment/asgn-10-java-app

          EOF

      
      - name: Test Deployment
        run: |
          echo "Waiting for app..."
          sleep 30
          curl -f http://${{ secrets.AWS_HOST }}:30004